/**
 * 总结持久化服务
 *
 * 负责将总结结果持久化到 Summary 表，提供历史查询和对比功能
 */
import { prisma } from '../database/prisma'
import {
  SummaryAnalysisResult,
  SentimentCurve,
  CategoryDistribution,
  TagStats,
  ImportanceDistribution,
  TaskCompletion,
  TimeDistribution,
} from '@daily-note/shared'

/**
 * Todo 完成统计（简化版）
 */
export interface TodoCompletionStats {
  total: number
  completed: number
  pending: number
  completionRate: number
}

/**
 * 总结数据模型（对应数据库表）
 */
export interface Summary {
  id: string
  mode: 'day' | 'week' | 'month' | 'year' | 'custom'
  startDate: Date
  endDate: Date

  // 总结内容
  overview: string
  achievements: string[]
  pendingTasks: string[]
  insights: string[]

  // 知识提炼
  keyLearnings?: string[]
  trends?: string[]
  patterns?: string[]
  recommendations?: string[]

  // 统计数据
  noteCount: number
  sentimentData: SentimentCurve
  categoryStats: CategoryDistribution[]
  tagStats: TagStats[]
  importanceStats: ImportanceDistribution
  taskStats: TaskCompletion
  timeStats: TimeDistribution
  todoStats: TodoCompletionStats // 新增

  // 元数据
  generatedAt: Date
  updatedAt: Date
  taskId: string
  isAutoGenerated: boolean
}

/**
 * 总结对比结果
 */
export interface SummaryComparison {
  base: Summary
  compare: Summary
  differences: {
    noteCountChange: number
    newAchievements: string[]
    completedTasks: string[]
    newInsights: string[]
    sentimentChange: string
  }
}

/**
 * 历史查询过滤器
 */
export interface SummaryHistoryFilters {
  mode?: string
  year?: number
  month?: number
  limit?: number
}

export class SummaryPersistenceService {
  /**
   * 生成 periodKey
   * @param mode - 总结模式
   * @param startDate - 开始日期
   * @returns periodKey
   */
  private generatePeriodKey(mode: string, startDate: Date): string {
    const date = new Date(startDate)

    switch (mode) {
      case 'day':
        return date.toISOString().split('T')[0]
      case 'week':
        const year = date.getFullYear()
        // 获取 ISO 周数
        const firstDayOfYear = new Date(year, 0, 1)
        const pastDaysOfYear = (date.getTime() - firstDayOfYear.getTime()) / 86400000
        const week = Math.ceil((pastDaysOfYear + firstDayOfYear.getDay() + 1) / 7)
        return `${year}-W${String(week).padStart(2, '0')}`
      case 'month':
        return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`
      case 'year':
        return String(date.getFullYear())
      default:
        return date.toISOString().split('T')[0]
    }
  }

  /**
   * 获取真实的 Todo 完成统计数据
   * @param startDate - 开始日期
   * @param endDate - 结束日期
   * @returns Todo 统计数据
   */
  async getRealTodoStats(startDate: string, endDate: string): Promise<TodoCompletionStats> {
    const start = new Date(startDate)
    const end = new Date(endDate)
    end.setHours(23, 59, 59, 999)

    const todos = await prisma.claudeTask.findMany({
      where: {
        type: 'todo',
        createdAt: { gte: start, lte: end },
      },
    })

    const total = todos.length
    const completed = todos.filter(t => t.status === 'COMPLETED').length
    const pending = total - completed
    const completionRate = total > 0 ? Math.round((completed / total) * 100) : 0

    return { total, completed, pending, completionRate }
  }

  /**
   * 保存或更新总结（使用 upsert 实现去重覆盖）
   *
   * @param result - 总结分析结果
   * @param taskId - 关联的任务 ID
   * @param mode - 总结模式
   * @param timeRange - 时间范围
   * @returns 保存的总结记录
   */
  async saveSummary(
    result: SummaryAnalysisResult,
    taskId: string,
    mode: string,
    timeRange: { startDate: string; endDate: string }
  ): Promise<Summary> {
    const periodKey = this.generatePeriodKey(mode, new Date(timeRange.startDate))
    const todoStats = await this.getRealTodoStats(timeRange.startDate, timeRange.endDate)

    const data = {
      mode,
      periodKey,
      startDate: new Date(timeRange.startDate),
      endDate: new Date(timeRange.endDate),
      overview: result.summary.overview,
      achievements: JSON.stringify(result.summary.keyAchievements),
      pendingTasks: JSON.stringify(result.summary.pendingTasks),
      insights: JSON.stringify(result.summary.insights),
      noteCount: result.period.noteCount,
      sentimentData: JSON.stringify(result.sentimentCurve),
      categoryStats: JSON.stringify(result.noteStatistics.categoryDistribution),
      tagStats: JSON.stringify(result.noteStatistics.topTags),
      importanceStats: JSON.stringify(result.noteStatistics.importanceDistribution),
      taskStats: JSON.stringify(result.taskCompletion),
      timeStats: JSON.stringify(result.timeDistribution),
      todoStats: JSON.stringify(todoStats),
      taskId,
      updatedAt: new Date(),
    }

    // 使用 upsert：存在则更新，不存在则创建
    const summary = await prisma.summary.upsert({
      where: { mode_periodKey: { mode, periodKey } },
      update: data,
      create: data,
    })

    return this.mapToSummary(summary)
  }

  /**
   * 获取总结历史列表
   *
   * @param filters - 过滤条件
   * @returns 总结列表
   */
  async getHistory(filters: SummaryHistoryFilters = {}): Promise<Summary[]> {
    const where: any = {}

    // 按模式筛选
    if (filters.mode) {
      where.mode = filters.mode
    }

    // 按年份/月份筛选
    if (filters.year || filters.month) {
      where.startDate = {}
      if (filters.year) {
        where.startDate.gte = new Date(filters.year, 0, 1)
        where.startDate.lte = new Date(filters.year, 11, 31)
      }
      if (filters.month) {
        const year = filters.year || new Date().getFullYear()
        where.startDate.gte = new Date(year, filters.month - 1, 1)
        where.startDate.lte = new Date(year, filters.month, 0)
      }
    }

    const summaries = await prisma.summary.findMany({
      where,
      orderBy: { startDate: 'desc' },
      take: filters.limit || 20,
    })

    return summaries.map((s) => this.mapToSummary(s))
  }

  /**
   * 获取单个总结详情
   *
   * @param id - 总结 ID
   * @returns 总结详情
   */
  async getById(id: string): Promise<Summary | null> {
    const summary = await prisma.summary.findUnique({
      where: { id },
    })

    return summary ? this.mapToSummary(summary) : null
  }

  /**
   * 根据 taskId 获取总结
   *
   * @param taskId - 任务 ID
   * @returns 总结详情
   */
  async getByTaskId(taskId: string): Promise<Summary | null> {
    // taskId 不再是唯一索引，使用 findFirst
    const summary = await prisma.summary.findFirst({
      where: { taskId },
    })

    return summary ? this.mapToSummary(summary) : null
  }

  /**
   * 对比两个总结
   *
   * @param summaryId1 - 第一个总结 ID
   * @param summaryId2 - 第二个总结 ID
   * @returns 对比结果
   */
  async compare(summaryId1: string, summaryId2: string): Promise<SummaryComparison> {
    const [s1, s2] = await Promise.all([
      prisma.summary.findUnique({ where: { id: summaryId1 } }),
      prisma.summary.findUnique({ where: { id: summaryId2 } }),
    ])

    if (!s1 || !s2) {
      throw new Error('Summary not found')
    }

    const summary1 = this.mapToSummary(s1)
    const summary2 = this.mapToSummary(s2)

    // 解析 JSON 数据
    const achievements1 = summary1.achievements
    const achievements2 = summary2.achievements
    const tasks1 = summary1.pendingTasks
    const tasks2 = summary2.pendingTasks
    const insights1 = summary1.insights
    const insights2 = summary2.insights

    return {
      base: summary1,
      compare: summary2,
      differences: {
        noteCountChange: summary2.noteCount - summary1.noteCount,
        newAchievements: achievements2.filter((a) => !achievements1.includes(a)),
        completedTasks: tasks1.filter((t) => !tasks2.includes(t)),
        newInsights: insights2.filter((i) => !insights1.includes(i)),
        sentimentChange: this.compareSentiment(summary1, summary2),
      },
    }
  }

  /**
   * 删除总结
   *
   * @param id - 总结 ID
   */
  async delete(id: string): Promise<void> {
    await prisma.summary.delete({
      where: { id },
    })
  }

  /**
   * 将数据库模型映射到领域模型
   *
   * @param dbSummary - 数据库模型
   * @returns 领域模型
   */
  private mapToSummary(dbSummary: any): Summary {
    return {
      id: dbSummary.id,
      mode: dbSummary.mode as any,
      startDate: dbSummary.startDate,
      endDate: dbSummary.endDate,
      overview: dbSummary.overview,
      achievements: JSON.parse(dbSummary.achievements),
      pendingTasks: JSON.parse(dbSummary.pendingTasks),
      insights: JSON.parse(dbSummary.insights),
      keyLearnings: dbSummary.keyLearnings ? JSON.parse(dbSummary.keyLearnings) : undefined,
      trends: dbSummary.trends ? JSON.parse(dbSummary.trends) : undefined,
      patterns: dbSummary.patterns ? JSON.parse(dbSummary.patterns) : undefined,
      recommendations: dbSummary.recommendations ? JSON.parse(dbSummary.recommendations) : undefined,
      noteCount: dbSummary.noteCount,
      sentimentData: JSON.parse(dbSummary.sentimentData),
      categoryStats: JSON.parse(dbSummary.categoryStats),
      tagStats: JSON.parse(dbSummary.tagStats),
      importanceStats: JSON.parse(dbSummary.importanceStats),
      taskStats: JSON.parse(dbSummary.taskStats),
      timeStats: JSON.parse(dbSummary.timeStats),
      todoStats: JSON.parse(dbSummary.todoStats || '{}'),
      generatedAt: dbSummary.generatedAt,
      updatedAt: dbSummary.updatedAt,
      taskId: dbSummary.taskId,
      isAutoGenerated: dbSummary.isAutoGenerated,
    }
  }

  /**
   * 对比心情变化
   *
   * @param s1 - 第一个总结
   * @param s2 - 第二个总结
   * @returns 心情变化描述
   */
  private compareSentiment(s1: Summary, s2: Summary): string {
    const trend1 = s1.sentimentData.trend
    const trend2 = s2.sentimentData.trend

    if (trend1 === trend2) {
      return `保持${trend1 === 'improving' ? '上升' : trend1 === 'declining' ? '下降' : '稳定'}趋势`
    }

    const trendMap = {
      improving: '上升',
      stable: '稳定',
      declining: '下降',
    }

    return `从${trendMap[trend1]}转为${trendMap[trend2]}`
  }
}

export const summaryPersistenceService = new SummaryPersistenceService()
